### ISSUE TITLE
Selhal import testovacích dat

### ISSUE THREAD

**Issue by Glutexo** [frenzymadness/donors_registry#65]
```
Imported 357598 records in 4040 batches
Traceback (most recent call last):
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1686, in _execute_context
    self.dialect.do_executemany(
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 713, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: awarded_medals.rodne_cislo, awarded_medals.medal_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/flask/cli.py", line 980, in main
    cli.main(args=sys.argv[1:])
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/flask/cli.py", line 596, in main
    return super().main(*args, **kwargs)
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/click/core.py", line 781, in main
    rv = self.invoke(ctx)
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/click/core.py", line 1227, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/click/core.py", line 1046, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/click/core.py", line 590, in invoke
    return callback(*args, **kwargs)
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/flask/cli.py", line 440, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/click/core.py", line 590, in invoke
    return callback(*args, **kwargs)
  File "/Users/glutexo/Vývoj/Registr dárců/donors_registry/registry/commands.py", line 30, in install_test_data
    test_data_medals(db)
  File "/Users/glutexo/Vývoj/Registr dárců/donors_registry/tests/utils.py", line 129, in test_data_medals
    db.session.commit()
  File "<string>", line 2, in commit
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1423, in commit
    self._transaction.commit(_to_root=self.future)
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3255, in flush
    self._flush(objects)
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3395, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3355, in _flush
    flush_context.execute()
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 453, in execute
    rec.execute(self)
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 627, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 242, in save_obj
    _emit_insert_statements(
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1094, in _emit_insert_statements
    c = connection._execute_20(
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1521, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1390, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1749, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1930, in _handle_dbapi_exception
    util.raise_(
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1686, in _execute_context
    self.dialect.do_executemany(
  File "/Users/glutexo/.local/share/virtualenvs/donors_registry-S2hq_ENW/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 713, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: awarded_medals.rodne_cislo, awarded_medals.medal_id
[SQL: INSERT INTO awarded_medals (rodne_cislo, medal_id) VALUES (?, ?)]
[parameters: (('0010126523', 1), ('0010126523', 2), ('0010126523', 3), ('0010126523', 4), ('0010126523', 5), ('0010126523', 6), ('0010126523', 7), ('0010147731', 1)  ... displaying 10 of 25293 total bound parameter sets ...  ('9962269196', 2), ('9962269196', 3))]
```

**Comment by Glutexo** [comment]
Planý poplach ~~asi~~.

**Comment by frenzymadness** [comment]
Oprava tohoto čeká na review v #62
